CREATE TABLE `T_HOTEL_BOOK_MANAGEMENT` (
  `hotel_name` VARCHAR(50) NOT NULL,
  `hotel_local` VARCHAR(50) NOT NULL,
  `group_id` VARCHAR(50) NULL,
  `book_begin_date` DATETIME NULL,
  `checkout_date` DATETIME NULL,
  `during_time` INT NULL,
  `partner_company` VARCHAR(20) NULL,
  `hotel_breakfast_flg` INT NULL,
  `hotel_lunch_flg` INT NULL,
  `hotel_supper_flg` INT NULL,
  `tour_person_count` INT NULL,
  `hotel_room_S` INT NULL,
  `priceof_room_S` INT NULL,
  `hotel_room_T` INT NULL,
  `priceof_room_T` INT NULL,
  `hotel_room_D` INT NULL,
  `priceof_room_D` INT NULL,
  `name_list` VARCHAR(200) NULL,
  `commission` INT NULL,
  `pay_type` VARCHAR(20) NULL,
  `linkman_name` VARCHAR(20) NULL,
  `linkman_tel` VARCHAR(20) NULL,
  `book_status` INT NOT NULL,
  `user_id` VARCHAR(10) NULL,
  PRIMARY KEY (`hotel_name`, `hotel_local`));